wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1675202478.472551
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 1
      - 2
      - 4
      - 5
      10:
      - 1
      - 9
dense_layer_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 10
first_layer_conv_height:
  desc: null
  value: 3
first_layer_conv_width:
  desc: null
  value: 3
img_height:
  desc: null
  value: 28
img_width:
  desc: null
  value: 28
