wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1675186759.164089
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 1
      - 2
      - 4
      - 5
